In [8]:
from sklearn.model_selection import KFold
kf = KFold(n_splits =3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [9]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [11]:
import numpy as np

In [12]:
from sklearn.datasets import load_iris
digits = load_iris()

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(digits.data,digits.target, test_size=0.3)

In [14]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

C:\Users\Accer\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9777777777777777

In [15]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.9555555555555556

In [16]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

0.9555555555555556

In [17]:
def get_score(model,X_train,X_test, y_train,y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [18]:
get_score(SVC(),X_train,X_test, y_train,y_test )

0.9555555555555556

In [19]:
from sklearn.model_selection import StratifiedKFold

In [20]:
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(iris.data, iris.targrt):
    X_train,X_test, y_train,y_test= iris.data[train_index], iris.data[test_index], \
                                    iris.target[train_index],iris.targrt[test_index]
    scores_logistic.append(get_score(lr = LogisticRegression(solver='liblinear', multi_class='ovr'),X_train,X_test, y_train,y_test))
    scores_SVM.append(get_score(SVC(gamma='auto'),X_train,X_test, y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40,X_train,X_test, y_train,y_test))

SyntaxError: positional argument follows keyword argument (1469194835.py, line 10)

In [21]:
scores_svm

NameError: name 'scores_svm' is not defined

In [ ]:
scores_ref

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'),iris.data, iris.target,cv = 3)

NameError: name 'iris' is not defined

In [24]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target,cv = 3)

NameError: name 'iris' is not defined

In [25]:
cross_val_score(SVC(gamma='auto'),iris.data, iris.target,cv = 3)

NameError: name 'iris' is not defined